apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "http-echo.fullname" . }}
  labels:
    {{- include "http-echo.labels" . | nindent 4 }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "http-echo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "http-echo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.env.HTTP_PORT | default 8080 }}
          protocol: TCP
        envFrom:
        - configMapRef:
            name: {{ include "http-echo.fullname" . }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
